
CXX		= $(GEO2D_CXX)
LD              = $(GEO2D_CXX)
LDFLAGS         += -Wl,-rpath,$(GEO2D_BASEDIR)/lib
FFLAGS          += -Wall
FLDFLAGS        += -lstdc++ -shared 
CXXFLAGS        += -g -O3 -W -Wall -Wno-deprecated -fPIC -D_CORE_$(shell uname -s)_
SOMAKER         = $(GEO2D_CXX)
SOFLAGS         = -g -fPIC -shared
